Fix sound script

diff --git a/files/home/.local/bin/sound b/files/home/.local/bin/sound
--- a/files/home/.local/bin/sound
+++ b/files/home/.local/bin/sound
@@ -2,8 +2,8 @@
 
 # Define your devices here
 declare -A devices
-devices["headset"]="1488 1487"
-devices["speaker"]="1506 74"
+devices["headset"]="alsa_input.usb-0c76_USB_PnP_Audio_Device-00.mono-fallback alsa_output.usb-0c76_USB_PnP_Audio_Device-00.iec958-stereo"
+devices["speaker"]="alsa_input.usb-046d_HD_Pro_Webcam_C920_12E8EDAF-02.iec958-stereo alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink"
 
 # Get the device pair from the first script argument
 device_pair=${devices[$1]}
@@ -15,8 +15,18 @@ fi
 
 # Split the device pair into input and output device names
 IFS=' ' read -ra device <<< "$device_pair"
-input_device_id=${device[0]}
-output_device_id=${device[1]}
+input_device=${device[0]}
+output_device=${device[1]}
+
+# Extract the current device ID from pactl
+input_device_id=$(pactl list short sources | grep "$input_device" | cut -f1)
+output_device_id=$(pactl list short sinks | grep "$output_device" | cut -f1)
+
+# Check if the device IDs were found
+if [ -z "$input_device_id" ] || [ -z "$output_device_id" ]; then
+  echo "Device ID not found"
+  exit 1
+fi
 
 if [ -z "$input_device_id" ]; then
   echo "Input device not found"
